---
- name: Configure server
  hosts: server
  sudo: True
  vars: 
    web_root: /var/www
  tasks:
   - name: install apache2
     apt: name=apache2 update_cache=yes
   - name: install iperf
     apt: name=iperf update_cache=yes
   - name: /usr/sbin/a2enmod status
     command: /usr/sbin/a2enmod status
   - name: check /etc/apache2/mods-enabled/status.conf file is absent   
     file: >
        path=/etc/apache2/mods-enabled/status.conf
        state=absent    
   - name: copy website/index.html into the web_root
     synchronize: src=website/index.html dest= {{ web_root }}
   - name: copy the website/graphics directory into /var/www
     synchronize: src=website/graphics dest=/var/www
   - name: rm -rf /var/www/html
     file: path=/var/www/html state=absent
   - name: Make simlink to webfiles
     file: >
        dest=/var/www/html
        src=/var/www/
        state=link
   - name: restart apache2 service
     service: name=apache2 state=restarted
   - name: Make sure /etc/apache2/conf.d/extendedstatus file contains "ExtendedStatus On"
     lineinfile: line='ExtendedStatus On' dest=/etc/apache2/conf.d/extendedstatus create=yes state=present
   - name: Make sure /etc/apache2/sites-available/default contains Location information
     lineinfile: 
       dest: /etc/apache2/sites-available/default  
       create: yes 
       state: present 
       insertafter: EOF 
       backup: yes
       regexp: "{{ item.regexp }}"
       line: "{{ item.line }}"
     with_items:
       - { regexp: '^<Location /server-status>', line: '<Location /server-status>' }
       - { regexp: '^   SetHandler server-status', line: '   SetHandler server-status' }
       - { regexp: '^   Allow from all', line: '   Allow from all' }
       - { regexp: '^</Location>', line: '</Location>' }
   - name: create directory for iperf logs in /var/www/iperflogs with permissions of 755
     file: >
        dest=/var/www/iperflogs
        state=directory
        mode=755
